/**
 * P2P Question Sync using Gun.js
 * 
 * Automatically syncs cached questions between students using a decentralized
 * peer-to-peer network. No manual link sharing required - all students using
 * the app automatically share their cached questions.
 * 
 * How it works:
 * 1. Gun.js creates a decentralized database that syncs across all peers
 * 2. When a student generates questions, they're automatically shared
 * 3. Other students receive these questions and cache them locally
 * 4. Questions are organized by appendix for efficient retrieval
 * 
 * This reduces API calls because students can use questions generated by others.
 */

const P2PSync = (function() {
    'use strict';

    // Gun.js instance
    let gun = null;
    let isInitialized = false;
    let syncEnabled = true;
    
    // App namespace to avoid conflicts with other Gun apps
    const APP_NAMESPACE = 'cpsa-quiz-v1';
    
    // Track what we've already synced to avoid duplicates
    const syncedQuestionHashes = new Set();
    
    // Callbacks for when new questions arrive
    const questionListeners = [];
    
    // Stats for debugging
    const stats = {
        questionsSent: 0,
        questionsReceived: 0,
        peersConnected: 0,
        lastSync: null
    };

    /**
     * Initialize Gun.js with public relay peers
     * These are free public Gun relay servers that help with peer discovery
     */
    function initialize() {
        if (isInitialized) {
            return Promise.resolve(true);
        }

        return new Promise((resolve) => {
            try {
                // Check if Gun is loaded
                if (typeof Gun === 'undefined') {
                    console.warn('P2PSync: Gun.js not loaded, P2P sync disabled');
                    syncEnabled = false;
                    resolve(false);
                    return;
                }

                // Initialize Gun with public relay peers for discovery
                // These are free public relays that help peers find each other
                gun = Gun({
                    peers: [
                        'https://gun-manhattan.herokuapp.com/gun',
                        'https://gun-us.herokuapp.com/gun'
                    ],
                    localStorage: false,  // We use our own IndexedDB cache
                    radisk: false         // Disable Gun's storage, use our cache
                });

                isInitialized = true;
                console.log('P2PSync: Initialized with Gun.js');
                
                // Start listening for questions from other peers
                startListening();
                
                resolve(true);
            } catch (error) {
                console.error('P2PSync: Failed to initialize', error);
                syncEnabled = false;
                resolve(false);
            }
        });
    }

    /**
     * Start listening for questions shared by other peers
     */
    function startListening() {
        if (!gun || !syncEnabled) return;

        // Listen for questions for each appendix (A-J)
        const appendices = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'];
        
        appendices.forEach(appendix => {
            const path = `${APP_NAMESPACE}/questions/${appendix}`;
            
            gun.get(path).map().on((data, key) => {
                if (!data || !key) return;
                
                try {
                    // Parse the question data
                    const question = typeof data === 'string' ? JSON.parse(data) : data;
                    
                    // Skip if we've already seen this question
                    const hash = hashQuestion(question.question || '');
                    if (syncedQuestionHashes.has(hash)) return;
                    
                    syncedQuestionHashes.add(hash);
                    stats.questionsReceived++;
                    stats.lastSync = new Date().toISOString();
                    
                    // Notify listeners about the new question
                    questionListeners.forEach(listener => {
                        try {
                            listener(question, appendix);
                        } catch (e) {
                            console.warn('P2PSync: Listener error', e);
                        }
                    });
                    
                    // Cache the question locally
                    cacheReceivedQuestion(question, appendix);
                    
                    console.log(`P2PSync: Received question for Appendix ${appendix} from peer`);
                } catch (e) {
                    // Ignore parse errors from malformed data
                }
            });
        });
        
        console.log('P2PSync: Listening for questions from peers');
    }

    /**
     * Share a question with other peers
     * @param {Object} question - The question object to share
     * @param {string} appendix - The appendix letter (A-J)
     */
    function shareQuestion(question, appendix) {
        if (!gun || !syncEnabled || !question) return;
        
        try {
            const hash = hashQuestion(question.question || '');
            
            // Don't share if we've already shared this question
            if (syncedQuestionHashes.has(hash)) return;
            
            syncedQuestionHashes.add(hash);
            
            // Create a clean question object for sharing
            const shareData = {
                question: question.question,
                options: question.options,
                correct: question.correct,
                explanation: question.explanation,
                section_id: question.section_id,
                section_title: question.section_title,
                appendix: appendix,
                sharedAt: Date.now()
            };
            
            // Store in Gun under the appendix path
            const path = `${APP_NAMESPACE}/questions/${appendix}`;
            gun.get(path).get(hash).put(JSON.stringify(shareData));
            
            stats.questionsSent++;
            stats.lastSync = new Date().toISOString();
            
            console.log(`P2PSync: Shared question for Appendix ${appendix}`);
        } catch (error) {
            console.warn('P2PSync: Failed to share question', error);
        }
    }

    /**
     * Share multiple questions at once
     * @param {Array} questions - Array of question objects
     * @param {string} appendix - The appendix letter
     */
    function shareQuestions(questions, appendix) {
        if (!Array.isArray(questions)) return;
        
        questions.forEach(q => shareQuestion(q, appendix));
    }

    /**
     * Cache a received question locally using QuestionCache
     */
    async function cacheReceivedQuestion(question, appendix) {
        if (typeof QuestionCache === 'undefined') return;
        
        try {
            // Create a chunk ID for caching (use section_id if available)
            const chunkId = question.source_chunk_id || 
                           `${appendix}_${question.section_id || 'unknown'}_p2p`;
            
            // Get existing cached questions for this chunk
            const existing = await QuestionCache.get(chunkId, {}) || [];
            
            // Check if question already exists
            const hash = hashQuestion(question.question);
            const exists = existing.some(q => hashQuestion(q.question) === hash);
            
            if (!exists) {
                // Add the new question
                existing.push({
                    ...question,
                    source_chunk_id: chunkId,
                    appendix: appendix,
                    fromP2P: true
                });
                
                // Save back to cache
                await QuestionCache.set(chunkId, existing, {
                    appendix: appendix,
                    sectionId: question.section_id
                }, {});
                
                console.log(`P2PSync: Cached P2P question for ${chunkId}`);
            }
        } catch (error) {
            console.warn('P2PSync: Failed to cache received question', error);
        }
    }

    /**
     * Simple hash function for question deduplication
     */
    function hashQuestion(text) {
        if (!text) return '0';
        const normalized = text.toLowerCase().replace(/[^\w\s]/g, '').replace(/\s+/g, ' ').trim();
        let hash = 2166136261;
        for (let i = 0; i < normalized.length; i++) {
            hash ^= normalized.charCodeAt(i);
            hash = (hash * 16777619) >>> 0;
        }
        return hash.toString(16);
    }

    /**
     * Register a callback for when new questions arrive from peers
     * @param {Function} callback - Called with (question, appendix) when new question arrives
     */
    function onQuestionReceived(callback) {
        if (typeof callback === 'function') {
            questionListeners.push(callback);
        }
    }

    /**
     * Remove a question listener
     */
    function offQuestionReceived(callback) {
        const index = questionListeners.indexOf(callback);
        if (index > -1) {
            questionListeners.splice(index, 1);
        }
    }

    /**
     * Get sync statistics
     */
    function getStats() {
        return { ...stats, syncEnabled, isInitialized };
    }

    /**
     * Enable or disable P2P sync
     */
    function setEnabled(enabled) {
        syncEnabled = enabled;
        console.log(`P2PSync: ${enabled ? 'Enabled' : 'Disabled'}`);
    }

    /**
     * Check if P2P sync is available and enabled
     */
    function isAvailable() {
        return isInitialized && syncEnabled;
    }

    // Public API
    return {
        initialize,
        shareQuestion,
        shareQuestions,
        onQuestionReceived,
        offQuestionReceived,
        getStats,
        setEnabled,
        isAvailable
    };
})();

// Auto-initialize when DOM is ready
if (typeof document !== 'undefined') {
    document.addEventListener('DOMContentLoaded', () => {
        P2PSync.initialize().then(success => {
            if (success) {
                console.log('P2P sync ready - questions will be shared automatically');
            }
        });
    });
}
